# Site settings
title: Himanshu Aggrawal
description: 'Yet another random guy'
url: 'http://himanshua.com/'
baseurl: 'http://himanshua.com'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Himanshu Aggrawal'
  email: himanshu@rice.edu
  twitter_username:
  facebook_username:
  github_username:
  linkedin_username: haggrawal

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
